#!/usr/bin/env bash
dir=${0%/*}
if [ "$dir" = "$0" ]; then dir="."; fi
cd "$dir" || exit

export WINEDEBUG="fixme-all,err-all"
PYEXE="$HOME/.wine/drive_c/windows/py.exe"
ISSEXE="$HOME/.wine/drive_c/Program Files (x86)/Inno Setup 6/ISCC.exe"
PYMAC="python3"
PYWIN="wine py"
VER=$(echo -e "import pypolona.__init__\nprint(pypolona.__init__.__version__)" | "$PYMAC")

function pp() {
  echo
  echo -e "[dist] $1"
  echo
}

function pins() {
  pp "Installing $1..."
}

function pup() {
  pp "Updating $1..."
}

function pok() {
  echo
  echo -e "\e[92m[dist] $1"
  echo
}

function perr() {
  echo
  echo -e "\e[91m[dist][ERROR] $1"
  echo
  exit
}

function pwarn() {
  echo
  echo -e "\e[91m[dist][WARNING] $1"
  echo
}

function insbrew() {
  if [ ! -x "$(command -v brew)" ]; then
    pins "brew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi
}

function pkgbrew() {
  # Install package if not installed
  # $ pkgbrew go
  if [ -z "$1" ]; then return; else local pkg=$@; fi
  insbrew
  if [ -x "$(touch $(brew --prefix)/var/testX6mg87lk)" ]; then
    pwarn "$(brew) needs to fix permissions, enter your administrator password:"
    sudo chown -R $(whoami) $(brew --prefix)/*
    sudo chown $(whoami) $(brew --prefix)/*
    brew list -1 | while read pkg; do
      brew unlink "$pkg"
      brew link "$pkg"
    done
  else
    rm "$(brew --prefix)/var/testX6mg87lk"
  fi
  if [ "$1" == "cask" ]; then
    local brewins="brew cask install"
    local brewupg="brew upgrade --cask"
    local brewlist="brew list --cask"
    local pkg=${@:2}
  else
    local brewins="brew install"
    local brewupg="brew upgrade"
    local brewlist="brew list"
  fi
  if $brewlist --versions "$pkg" >/dev/null; then
    pup "$brewupg:$pkg"
    HOMEBREW_NO_AUTO_UPDATE=1 $brewupg "$pkg"
  else
    pins "$brewins:$pkg"
    HOMEBREW_NO_AUTO_UPDATE=1 $brewins "$pkg"
  fi
}

function brewapp() {
  # $ brewapp package # if command=package
  # $ brewapp command package # if command!=package
  if [ -z "$1" ]; then return; else local cmd="$1"; fi
  if [ -z "$2" ]; then local pkg="$cmd"; else local pkg=${@:2}; fi
  pkgbrew $pkg && return 1
}

function getapp() {
  if [ -z "$1" ]; then
    return 2
  else
    command -v "$1" && return 0
  fi
}

function preppy() {
  pins "Python Mac packages"
  $PYMAC -m pip install --user --upgrade setuptools wheel pip
  $PYMAC -m pip install --user --upgrade -r requirements.txt
  $PYMAC -m pip install --user --upgrade -e .[dev]
  pins "Python Win packages"
  $PYWIN -m pip install --user --upgrade setuptools wheel pip
  $PYWIN -m pip install --user --upgrade -r requirements.txt
  $PYWIN -m pip install --user --upgrade -e .[dev]
}

function prep() {
  brewapp wine cask wine-staging
  if [ ! -f "$PYEXE" ]; then
    pins "wine py"
    curl -L -o "$TMPDIR/python.exe" https://www.python.org/ftp/python/3.8.5/python-3.8.5-amd64.exe &&
      wine "$TMPDIR/python.exe" /quiet &&
      rm "$TMPDIR/python.exe"
  fi
  if [ ! -f "$ISSEXE" ]; then
    pins "wine iss"
    curl -L -o "$TMPDIR/iss.exe" https://jrsoftware.org/download.php/is.exe &&
      wine "$TMPDIR/iss.exe" /VERYSILENT &&
      rm "$TMPDIR/iss.exe"
  fi
  brewapp upx
  brewapp grealpath coreutils
  brewapp python3 python
  preppy
}

function install() {
  pp "## Installing"
  $PYMAC -m pip install --user --upgrade -e .[dev]
}

function buildpy() {
  pp "## Building wheel"
  rm -rf dist/*
  $PYMAC setup.py sdist bdist_wheel
}

function buildmac() {
  pp "## Building Mac DMG"
  $PYMAC -m PyInstaller \
    --distpath="$cwd/app/build/dist-mac" \
    --workpath="$cwd/app/build" \
    -y "app/pyinstaller-mac.spec"
  dmgbuild -s dmgbuild_settings.py "PyPolona" "download/pypolona-mac.dmg"
  #rm -rf "$cwd/app/build/dist-mac"
}

function iss() {
  wine "$ISSEXE" /dMyAppVersion="$VER" app/pypolona.iss /Q
}

function buildwin() {
  pp "## Building Win EXE"
  $PYWIN -m pip install --user --upgrade -e .[dev]
  $PYWIN -m PyInstaller \
    --distpath="$cwd/app/build/dist-win" \
    --workpath="$cwd/app/build" \
    -y "app/pyinstaller-win.spec"
  pp "## Building Win EXE installer"
  wine "$ISSEXE" /dMyAppVersion="$VER" app/pypolona.iss /Q
  pp "## Building Win ZIP"
  rm -rf "download/pypolona-win.zip" && zip -j "download/pypolona-win.zip" "app/build/dist-win/setup_pypolona.exe"
}

function build() {
  echo "## Pushing to Github"
  git add --all
  git commit -am "Build: v$version: $text"
  git pull
  git push

  buildpy
  buildmac
  buildwin
}

function publish() {
  [ -z "$2" ] && text="update" || text="$2"

  echo "## Pushing to Github"
  git add --all
  git commit -am "Release: v$version: $text"
  git pull
  git push

  branch=$(git rev-parse --abbrev-ref HEAD)
  token=$(git config --global github.token)

  repo_full_name=$(git config --get remote.origin.url)
  url=$repo_full_name
  re="^(https|git)(:\/\/|@)([^\/:]+)[\/:]([^\/:]+)\/(.+).git$"
  if [[ $url =~ $re ]]; then
    protocol=${BASH_REMATCH[1]}
    separator=${BASH_REMATCH[2]}
    hostname=${BASH_REMATCH[3]}
    user=${BASH_REMATCH[4]}
    repo=${BASH_REMATCH[5]}
  fi

  generate_post_data() {
    cat <<EOF
{
  "tag_name": "$version",
  "target_commitish": "$branch",
  "name": "$version",
  "body": "$text",
  "draft": false,
  "prerelease": false
}
EOF
  }

  echo "## Creating release $version for repo: $repo_full_name branch: $branch"
  curl --data "$(generate_post_data)" "https://api.github.com/repos/$user/$repo/releases?access_token=$token"

  echo
  echo "## Publishing on https://pypi.org/project/pypolona/"
  echo "Enter your pypi.org login and password:"

  python3 -m twine upload --verbose -c "$text" dist/*
  open "https://pypi.org/project/pypolona/"

  echo "## Pushing to Github"
  git add --all
  git commit -am "Published: v$VER: $text"
  git pull
  git push
}

function init() {
  upx=$(getapp upx) || prep
  grealpath=$(getapp grealpath) || prep
  python3=$(getapp "$PYMAC") || prep
  cwd=$("$grealpath" "$dir")
}

function usage() {
  echo "Usage: ""$0 build | publish [releasetext]; "
}

function all() {
  prep
  install
  build
  publish "$1"
}

function main() {
  init
  if [ $# -eq 0 ]; then
    usage
    exit $?
  fi

  case $1 in
  help)
    usage
    exit $?
    ;;
  init) init ;;
  prep) prep ;;
  preppy) preppy ;;
  install) install ;;
  build) build ;;
  buildpy) buildpy ;;
  buildmac) buildmac ;;
  buildwin) buildwin ;;
  publish) publish $@ ;;
  all) all $@ ;;
  esac
}

main $@
